name: "Neolink"
description: "Will run Neolink directly as Add-on in HAOS"
version: "0.0.9"
slug: "neolink"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - i386
  - armv7
ports:
  8555/tcp: 8555
map:
  - config
options:
  mode: rtsp
  log: info
schema:
  mode: list(rtsp|mqtt|dual)
  log: list(info|warn|error|debug)
